### ISSUE TITLE
undefined method `minutes_left'

### ISSUE THREAD

**Issue by oparoz** [ari/jobsworth#498] opened 2014-01-30 19:08 UTC
Using master, go to "My account" and click on "Work Plan"
URL: users/3/workplan

The app crashes with this message
```ruby
ActionView::Template::Error (undefined method `minutes_left' for #<Template:0x00000809de9778>):
    5: <div class="<%= user.top_next_task == task ? 'top-next-task' : nil %>">
    6:   <%= human_future_date(pill_date, user.tz) %>
    7:   <span class="<%= task.css_classes %>">
    8:     <%= link_to "<b>##{task.task_num}</b>".html_safe, task_view_path(task.task_num), 'data-taskid' => task.id, "data-content" => task_detail(task, user) %>
    9:     <%= task.name %>
    10:
    11:     <% case time %>
app/helpers/tasks_helper.rb:253:in `task_detail'
```

**Comment by nasa42** [comment] 2015-05-27 06:56
I'm closing this issue because we were never able to reproduce it in last one year.
@oparoz, feel free to reopen if you are still encountering this issue.

**Closed by nasa42** 2015-05-27 06:56 UTC
