### ISSUE TITLE
attach: cannot add any attachment to a task

### ISSUE THREAD

**Issue by akoyro** [ari/jobsworth#640] opened 2016-07-07 09:46 UTC
1. attach any file
2. press save

Result: 
Forbidden

You don't have permission to access /tasks/29385 on this server.

**Comment by ari** [comment] 2016-07-07 10:12
I'm going to close this. Looks like the issue is in our firewall application filter layer being too enthusiastic with some attachments.

**Closed by ari** 2016-07-07 10:12 UTC
Labels: high priority
