### ISSUE TITLE
Installing jobsworth does not work like described in README.rdoc

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#641] opened 2016-07-09 18:44 UTC
Honestly, I am not sure if somebody has been really able before to install jobsworth like described in README.rdoc – for me it did simply *not* *work* as described. For the sake of completeness, I am listing my steps here, run at CentOS 7:

  * `yum install postgresql-server tomcat`
  * `postgresql-setup initdb`
  * Add new line with e.g. the following on top of `/var/lib/pgsql/data/pg_hba.conf`:
```
host jobsworth jobsworth 127.0.0.1/32 password
```
  * `systemctl enable --now postgresql.service`
  * `createuser -P jobsworth` and set a password, e.g. `tux`
  * `createdb -O jobsworth jobsworth`
  * `cd /var/lib/tomcat/webapps/`
  * `wget https://github.com/ari/jobsworth/releases/download/5.0M3/ROOT.war`
  * `wget https://raw.githubusercontent.com/ari/jobsworth/master/config/context.example.xml -O /etc/tomcat/context.xml`
  * Edit `<Resource>` tag in `/etc/tomcat/context.xml` as follows:
```
<Resource name="jdbc/jobsworth" removeAbandoned="true" auth="Container" type="javax.sql.DataSource" maxActive="100" maxIdle="30" maxWait="10000" username="jobsworth" password="tux" driverClassName="org.postgresql.Driver" batchSize="-1" url="jdbc:postgresql://localhost:5432/jobsworth?user=jobsworth&amp;password=tux" validationQuery="select 1"/>
```
  * `systemctl enable --now tomcat.service`
  * Visit `http://localhost:8080` and get welcome with:  

> jdbc adapter requires :driver and :url (got :driver = mysql) from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/connection.rb:89:in `setup_jdbc_factory' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/connection.rb:56:in `setup_connection_factory' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/connection.rb:14:in `initialize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:76:in `initialize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:44:in `new' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/connection_methods.rb:12:in `jdbc_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/migration.rb:24:in `current_version' from /var/lib/tomcat/webapps/ROOT/WEB-INF/config/initializers/020_database_migration.rb:24:in `<top>' from org/jruby/RubyKernel.java:962:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:1:in `block in (root)' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:652:in `load_config_initializer' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:651:in `block in load_config_initializer' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block in Engine' from org/jruby/RubyBasicObject.java:1684:in `instance_exec' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:422:in `block in each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:420:in `block in each_strongly_connected_component_from' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child' from org/jruby/RubyMethod.java:115:in `call' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:415:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component' from org/jruby/RubyArray.java:1593:in `each' from org/jruby/RubyMethod.java:127:in `call' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:615:in `Engine' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226:in `tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205:in `tsort_each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers' from org/jruby/RubyKernel.java:1812:in `public_send' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `<top>' from org/jruby/RubyKernel.java:944:in `require' from /usr/share/tomcat/webapps/ROOT/WEB-INF/config/environment.rb:5:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:25:in `<top>' 

  * Figure out that `factory="org.apache.commons.dbcp.BasicDataSourceFactory"` should be added if `org.apache.tomcat.dbcp.dbcp.BasicDataSourceFactory` does not exist (which is the default on CentOS 7 at least, thus might be a CentOS specific issue)
  * Edit `<Resource>` tag in `/etc/tomcat/context.xml` again, now as follows:  
```
<Resource name="jdbc/jobsworth" removeAbandoned="true" auth="Container" type="javax.sql.DataSource" maxActive="100" maxIdle="30" maxWait="10000" username="jobsworth" password="tux" driverClassName="org.postgresql.Driver" factory="org.apache.commons.dbcp.BasicDataSourceFactory" batchSize="-1" url="jdbc:postgresql://localhost:5432/jobsworth?user=jobsworth&amp;password=tux" validationQuery="select 1"/>
```
  * `systemctl restart tomcat.service`
  * Visit `http://localhost:8080` and get welcome with:  

> org.postgresql.util.PSQLException: ERROR: syntax error at or near "utf8" Position: 11 from arjdbc/jdbc/RubyJdbcConnection.java:587:in `execute' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:595:in `_execute' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:569:in `execute' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/mysql/adapter.rb:77:in `configure_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:85:in `initialize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/adapter.rb:44:in `new' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/jdbc/connection_methods.rb:12:in `jdbc_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/migration.rb:24:in `current_version' from /var/lib/tomcat/webapps/ROOT/WEB-INF/config/initializers/020_database_migration.rb:24:in `<top>' from org/jruby/RubyKernel.java:962:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:1:in `block in (root)' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:652:in `load_config_initializer' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:651:in `block in load_config_initializer' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block in Engine' from org/jruby/RubyBasicObject.java:1684:in `instance_exec' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:422:in `block in each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:420:in `block in each_strongly_connected_component_from' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child' from org/jruby/RubyMethod.java:115:in `call' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:415:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component' from org/jruby/RubyArray.java:1593:in `each' from org/jruby/RubyMethod.java:127:in `call' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:615:in `Engine' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226:in `tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205:in `tsort_each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers' from org/jruby/RubyKernel.java:1812:in `public_send' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `<top>' from org/jruby/RubyKernel.java:944:in `require' from /usr/share/tomcat/webapps/ROOT/WEB-INF/config/environment.rb:5:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:25:in `<top>' 

  * Look into the PostgreSQL log file and figure out that MySQL (?) specific SQL commands get fired by jobsworth to a PostgreSQL database:

> ERROR:  syntax error at or near "utf8" at character 11
> STATEMENT:  SET NAMES utf8,  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES' RETURNING *

  * Figure out that `/var/lib/tomcat/webapps/ROOT/WEB-INF/config/database.yml` contains  
```
production:
  adapter: jdbc
  driver: mysql
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8
  pool: 100
```
  * Replace that definately wrong MySQL related block in `/var/lib/tomcat/webapps/ROOT/WEB-INF/config/database.yml` by something more suitable (inspired by `/var/lib/tomcat/webapps/ROOT/WEB-INF/config/database.postgres.yml`):
```
production:
  adapter: jdbcpostgresql
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8
  schema_search_path: public
  min_messages: warning
```
  * `systemctl restart tomcat.service`
  * Visit `http://localhost:8080` and get welcome with the login page

The question that still remains is whether hacking the `/var/lib/tomcat/webapps/ROOT/WEB-INF/config/database.yml` file was correct. It was definately needed to get something working at all, but is the new `production` section correct through?

Last but not least: There is a tiny difference between above and README.rdoc (points such as PostgreSQL and Tomcat installation/configuration are indeed out of scope).

**Comment by ari** [comment] 2016-07-11 11:08
Thanks for your detailed notes. To be honest it has been a long time since I've tried to install it all from scratch since our production system has been continuously updated for about 10 years.

But we'll make some time and try and reproduce your process.

**Comment by ari** [comment] 2016-07-11 11:13
@k41n Although I don't think it solves all the issues above, we could look at #555 to avoid the whole tomcat configuration part. But then we still need to understand where the config files should be placed outside the war/executable and what sort of script is needed to start/stop.

**Comment by ari** [comment] 2016-07-14 02:47
I've released https://github.com/ari/jobsworth/releases/tag/5.0b1 so please try again. Let's look at your problems:

1. org.apache.commons.dbcp.BasicDataSourceFactory I think is not needed. We'll I don't use it.

2. database.yml points to mysql. Now fixed.

3. Some of the records were not being created on startup (such as a new blank project). This is fixed so that you should be able to now get started without creating any records by hand.


@robert-scheck Please try again and let me know if it now works more smoothly.

**Comment by robert-scheck** [comment] 2016-09-03 18:07
> org.apache.commons.dbcp.BasicDataSourceFactory I think is not needed. We'll I don't use it.

I am sorry, but this is not correct. You depend on `org.apache.tomcat.dbcp.dbcp.BasicDataSourceFactory` for some reason, and if you are not running precompiled Tomcat from http://tomcat.apache.org/ – but just the Tomcat that is shipped with CentOS 7, then you definately need to add `factory="org.apache.commons.dbcp.BasicDataSourceFactory"` as a substitution to make things working at all.

Unfortunately database related stuff is still somehow broken, 5.0 beta 1 simply leads to:

> undefined method `get_oid_type' for #<ActiveRecord::ConnectionAdapters::JdbcAdapter:0x51547cea> from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/postgresql/adapter.rb:1262:in `block in columns' from org/jruby/RubyArray.java:2387:in `map!' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.20/lib/arjdbc/postgresql/adapter.rb:1256:in `columns' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/attributes.rb:93:in `columns' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/attributes.rb:98:in `columns_hash' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/querying.rb:41:in `find_by_sql' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/relation.rb:639:in `exec_queries' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/relation.rb:515:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/relation.rb:243:in `to_a' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `map' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/migration.rb:847:in `get_all_versions' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.6/lib/active_record/migration.rb:854:in `current_version' from /var/lib/tomcat/webapps/ROOT/WEB-INF/config/initializers/020_database_migration.rb:24:in `<top>' from org/jruby/RubyKernel.java:962:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:1:in `block in (root)' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:652:in `load_config_initializer' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:651:in `block in load_config_initializer' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block in Engine' from org/jruby/RubyBasicObject.java:1684:in `instance_exec' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:422:in `block in each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:420:in `block in each_strongly_connected_component_from' from org/jruby/RubyArray.java:1593:in `each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child' from org/jruby/RubyMethod.java:115:in `call' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:415:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component' from org/jruby/RubyArray.java:1593:in `each' from org/jruby/RubyMethod.java:127:in `call' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/engine.rb:615:in `Engine' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226:in `tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205:in `tsort_each' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers' from org/jruby/RubyKernel.java:1812:in `public_send' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!' from /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `<top>' from org/jruby/RubyKernel.java:944:in `require' from /usr/share/tomcat/webapps/ROOT/WEB-INF/config/environment.rb:5:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:25:in `<top>' 

File `/var/lib/tomcat/webapps/ROOT/WEB-INF/config/database.yml` contains:

```
development:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8

test:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8

production:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8
  pool: 100
```

Changing at least `adapter: jdbc` to `adapter: jdbcpostgresql` makes things working. So where does the wrong `adapter: jdbc` come from? This was also part of my initial report – aside of this the rest is fixed as it seems :)

Please reopen for the remaining issue, thank you.

**Comment by robert-scheck** [comment] 2016-09-03 18:21
By the way, removing `adapter: jdbc` completely is not a good idea…that just leads to another error.

**Comment by ari** [comment] 2016-09-08 06:56
Opening to see what is happening with 

`adapter: jdbc`

**Comment by riahc3** [comment] 2016-09-21 16:52
I am almost 100% sure that it cannot be installed on a standalone server.

I've tried Debian, FreeBSD, Ubuntu, etc....impossible. At some random point it errors out.

The fact that the author for some reason refuses to make a decent install guide, makes me suspicious.

**Comment by ari** [comment] 2016-09-21 22:34
@riahc3 Suspicious of what? There is an install guide in the README. Are you expecting me to come around to your place and install it for you?

**Comment by robert-scheck** [comment] 2016-09-21 22:39
@ari, even if @riahc3's comment is inappropriate here, could we still focus on remaining issue with `adapter: jdbc`, please?

**Comment by ari** [comment] 2016-09-21 23:25
@robert-scheck Sure. Actually I thought we solved that one.

@k41n Did we need to downgrade a gem to fix this, or did you already sort it out?

**Comment by riahc3** [comment] 2016-09-22 08:22
@ari I ment suspicious in the sense of wanting to use your servers instead of a standalone server.

Im not sure how you took the comment...I just ment that.

Its very frustrating not being able to run this on a standalone server.

**Comment by riahc3** [comment] 2016-09-22 15:05
@ari Also that README file has not been updated in a long time because as you can see users posting out errors in the documentation.

**Comment by ari** [comment] 2016-09-23 02:12
@riahc3 Please don't hijack this task. Either be constructive with requests for specific assistance or details of your problems or go away.

**Comment by riahc3** [comment] 2016-09-23 12:03
Ari,


Thank you for writing.


I dont mean to hijack or be rude...Its frustrating just searching for ways how to install this (or ClockingIT) and find so many roadblocks and so little solutions.


Im actually suprised there isnt any up to date information as I would have thought you would have liked more people to use your project.


I apoligize for any inconvience


________________________________

**Comment by ari** [comment] 2016-10-02 03:11
The only issue that appears to remain here is #670 so I'll close this task now. Let's continue anything specific to JDBC adapter in the other more focussed task.

**Closed by ari** 2016-10-02 03:11 UTC
Labels: regression
